# Generated by Django 4.0.4 on 2022-05-02 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppJuegos', '0002_coleccion_pago_ps4_xbox_delete_miembros'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coleccion',
            options={'verbose_name': 'Coleccion', 'verbose_name_plural': 'Colecciones'},
        ),
        migrations.AlterModelOptions(
            name='ps4',
            options={'verbose_name': 'Ps4', 'verbose_name_plural': 'Ps4'},
        ),
        migrations.AlterModelOptions(
            name='xbox',
            options={'verbose_name': 'Xbox', 'verbose_name_plural': 'Xbox'},
        ),
    ]
